name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Riru modules
        run: ls riru/Riru-ModuleTemplate
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_STORE_BASE64 }}
        run: echo $ENCODED_STRING | base64 -di > app/keystore.jks
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build Riru modules
        run: cd ./riru && bash ./make.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean ":app:assembleRelease"
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload Apk
        uses: actions/upload-artifact@v2.2.0
        with:
          name: xposed.${{ steps.current-time.outputs.formattedTime }}.zip
          path: app/build/outputs/apk/release/*.apk
      - name: Upload Riru Modules
        uses: actions/upload-artifact@v2.2.0
        with:
          name: magisk.${{ steps.current-time.outputs.formattedTime }}.zip
          path: |
            riru/build/release/*.zip
            !riru/build/release/*-all-*.zip
      - name: Assign release version from version.properties to Env variable
        run: |
          cat ./app/build.gradle| grep versionName | sed -E 's/.+"(.+)".*/release_version=\1/g' >> $GITHUB_ENV
      - name: Echo release version from  Env variable
        run: |
          echo "${{ env.release_version }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: "${{ env.release_version }}"
          tag_name: "${{ env.release_version }}"
          files: |
            app/build/outputs/apk/release/*.apk
            riru/build/release/*.zip
          body: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"